"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 05:30:40.498387
"""

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facilities")),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("room", sa.String(length=64), nullable=True),
        sa.Column("floor", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "UNPROVISIONED",
                "ONLINE",
                "DEGRADED",
                "OFFLINE",
                name="devicestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("firmware_version", sa.String(length=64), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_uptime_seconds", sa.Integer(), nullable=True),
        sa.Column("last_rssi_dbm", sa.Integer(), nullable=True),
        sa.Column("last_temperature_c", sa.Float(), nullable=True),
        sa.Column("last_power_state", sa.String(length=32), nullable=True),
        sa.Column("last_free_psram_bytes", sa.Integer(), nullable=True),
        sa.Column("buffer_effective_seconds", sa.Float(), nullable=True),
        sa.Column("reported_faults", sa.JSON(), nullable=False),
        sa.Column("pending_commands", sa.JSON(), nullable=False),
        sa.Column("credential_hash", sa.String(length=64), nullable=False),
        sa.Column("credential_rotated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"], ["facilities.id"], name=op.f("fk_devices_facility_id_facilities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
    )
    op.create_index(
        "ix_devices_facility_status", "devices", ["facility_id", "status"], unique=False
    )
    op.create_table(
        "residents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("room", sa.String(length=64), nullable=True),
        sa.Column("floor", sa.String(length=32), nullable=True),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="risklevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISCHARGED", name="residentstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"], ["facilities.id"], name=op.f("fk_residents_facility_id_facilities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_residents")),
    )
    op.create_index(
        "ix_residents_location", "residents", ["facility_id", "floor", "room"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "SUPERVISOR",
                "NURSE",
                "CAREGIVER",
                name="userrole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", name="userstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("on_duty", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"], ["facilities.id"], name=op.f("fk_users_facility_id_facilities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_facility_id"), "users", ["facility_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_device_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_device_id"], ["devices.id"], name=op.f("fk_audit_logs_actor_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"], ["facilities.id"], name=op.f("fk_audit_logs_facility_id_facilities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_facility_at", "audit_logs", ["facility_id", "at"], unique=False)
    op.create_table(
        "care_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "PRIMARY",
                "SECONDARY",
                "SUPERVISOR",
                "EMERGENCY",
                name="caretier",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("floor", sa.String(length=32), nullable=True),
        sa.Column("room", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
            name=op.f("fk_care_assignments_facility_id_facilities"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_care_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_care_assignments")),
    )
    op.create_index(
        "ix_care_assignments_scope",
        "care_assignments",
        ["facility_id", "floor", "room"],
        unique=False,
    )
    op.create_table(
        "device_status_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "UNPROVISIONED",
                "ONLINE",
                "DEGRADED",
                "OFFLINE",
                name="devicestatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "UNPROVISIONED",
                "ONLINE",
                "DEGRADED",
                "OFFLINE",
                name="devicestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_status_events_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_status_events")),
    )
    op.create_index(
        "ix_device_status_events_device_at",
        "device_status_events",
        ["device_id", "at"],
        unique=False,
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("resident_id", sa.Uuid(), nullable=True),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("device_event_id", sa.String(length=64), nullable=False),
        sa.Column(
            "incident_type",
            sa.Enum("FALL", name="incidenttype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "SUSPICIOUS",
                "POTENTIAL_FALL",
                "CONFIRMED_FALL",
                "ALERT_SENT",
                "ESCALATED",
                "ACKNOWLEDGED",
                "RESPONDING",
                "RESOLVED",
                "FALSE_POSITIVE",
                "CANCELLED",
                "UNRESOLVED",
                name="incidentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "HIGH", "CRITICAL", name="priority", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("room", sa.String(length=64), nullable=True),
        sa.Column("floor", sa.String(length=32), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_level", sa.String(length=16), nullable=False),
        sa.Column("trigger_score", sa.Float(), nullable=False),
        sa.Column("verifier_score", sa.Float(), nullable=True),
        sa.Column("immobility_seconds", sa.Float(), nullable=False),
        sa.Column("trigger_count", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("escalation_level", sa.Integer(), nullable=False),
        sa.Column("next_escalation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.Uuid(), nullable=True),
        sa.Column("responding_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responding_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolution_note", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"], ["users.id"], name=op.f("fk_incidents_acknowledged_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_incidents_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"], ["facilities.id"], name=op.f("fk_incidents_facility_id_facilities")
        ),
        sa.ForeignKeyConstraint(
            ["resident_id"], ["residents.id"], name=op.f("fk_incidents_resident_id_residents")
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"], ["users.id"], name=op.f("fk_incidents_resolved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["responding_by"], ["users.id"], name=op.f("fk_incidents_responding_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
        sa.UniqueConstraint("device_id", "device_event_id", name="uq_incidents_device_event"),
    )
    op.create_index(
        "ix_incidents_escalation_due", "incidents", ["next_escalation_at"], unique=False
    )
    op.create_index(
        "ix_incidents_facility_detected", "incidents", ["facility_id", "detected_at"], unique=False
    )
    op.create_index(
        "ix_incidents_facility_status", "incidents", ["facility_id", "status"], unique=False
    )
    op.create_table(
        "evidence_clips",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("segment", sa.String(length=16), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("first_frame_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_frame_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_evidence_clips_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_clips")),
    )
    op.create_index("ix_evidence_clips_expires", "evidence_clips", ["expires_at"], unique=False)
    op.create_table(
        "incident_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "SUSPICIOUS",
                "POTENTIAL_FALL",
                "CONFIRMED_FALL",
                "ALERT_SENT",
                "ESCALATED",
                "ACKNOWLEDGED",
                "RESPONDING",
                "RESOLVED",
                "FALSE_POSITIVE",
                "CANCELLED",
                "UNRESOLVED",
                name="incidentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "SUSPICIOUS",
                "POTENTIAL_FALL",
                "CONFIRMED_FALL",
                "ALERT_SENT",
                "ESCALATED",
                "ACKNOWLEDGED",
                "RESPONDING",
                "RESOLVED",
                "FALSE_POSITIVE",
                "CANCELLED",
                "UNRESOLVED",
                name="incidentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("note", sa.String(length=2000), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_incident_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_events_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_events")),
    )
    op.create_index(
        "ix_incident_events_incident_at", "incident_events", ["incident_id", "at"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "in_app",
                "push",
                "sms",
                "email",
                name="notificationchannel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("tier", sa.String(length=16), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=1000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "DELIVERED",
                "ACKNOWLEDGED",
                "FAILED",
                "CANCELLED",
                name="notificationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_notifications_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"], ["users.id"], name=op.f("fk_notifications_recipient_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index("ix_notifications_incident", "notifications", ["incident_id"], unique=False)
    op.create_index(
        "ix_notifications_recipient_status",
        "notifications",
        ["recipient_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_recipient_status", table_name="notifications")
    op.drop_index("ix_notifications_incident", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_incident_events_incident_at", table_name="incident_events")
    op.drop_table("incident_events")
    op.drop_index("ix_evidence_clips_expires", table_name="evidence_clips")
    op.drop_table("evidence_clips")
    op.drop_index("ix_incidents_facility_status", table_name="incidents")
    op.drop_index("ix_incidents_facility_detected", table_name="incidents")
    op.drop_index("ix_incidents_escalation_due", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_device_status_events_device_at", table_name="device_status_events")
    op.drop_table("device_status_events")
    op.drop_index("ix_care_assignments_scope", table_name="care_assignments")
    op.drop_table("care_assignments")
    op.drop_index("ix_audit_logs_facility_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_facility_id"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_residents_location", table_name="residents")
    op.drop_table("residents")
    op.drop_index("ix_devices_facility_status", table_name="devices")
    op.drop_table("devices")
    op.drop_table("facilities")
    # ### end Alembic commands ###
